# Generated by Django 2.1.7 on 2019-03-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('year', models.CharField(max_length=4)),
                ('imdbID', models.CharField(max_length=12)),
                ('movie_type', models.PositiveIntegerField(choices=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode'), ('game', 'game')])),
                ('poster_url', models.CharField(max_length=128)),
            ],
        ),
    ]
