# Generated by Django 2.1.7 on 2019-03-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdbID',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
