# Generated by Django 2.1.7 on 2019-03-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_favourites', '0002_auto_20190304_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_type',
            field=models.PositiveIntegerField(choices=[(1, 'movie'), (2, 'series'), (3, 'episode'), (4, 'game')]),
        ),
    ]
